version: "3.8"

services:
  yakiimo-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - yakiimo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yakiimo-user
      POSTGRES_PASSWORD: yakiimo-pass
      POSTGRES_DB: yakiimo-db
      TZ: Asia/Tokyo

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=ses
      - AWS_DEFAULT_REGION=ap-northeast-1

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  yakiimo_data:
